// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	CreateUserRequest
	CreateUserResponse
	GetSessionRequest
	GetSessionResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	FirstName string                      `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string                      `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Email     string                      `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Password  string                      `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	Age       int32                       `protobuf:"varint,5,opt,name=age" json:"age,string,omitempty"`
	Role      string                      `protobuf:"bytes,6,opt,name=role" json:"role,omitempty"`
	Location  *CreateUserRequest_Location `protobuf:"bytes,7,opt,name=location" json:"location,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CreateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *CreateUserRequest) GetLocation() *CreateUserRequest_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type CreateUserRequest_Location struct {
	City    string `protobuf:"bytes,1,opt,name=city" json:"city,omitempty"`
	Country string `protobuf:"bytes,2,opt,name=country" json:"country,omitempty"`
}

func (m *CreateUserRequest_Location) Reset()                    { *m = CreateUserRequest_Location{} }
func (m *CreateUserRequest_Location) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest_Location) ProtoMessage()               {}
func (*CreateUserRequest_Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *CreateUserRequest_Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CreateUserRequest_Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type CreateUserResponse struct {
	Status  string                      `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string                      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Token   string                      `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	Fields  []*CreateUserResponse_Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateUserResponse) GetFields() []*CreateUserResponse_Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type CreateUserResponse_Field struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Validation string `protobuf:"bytes,2,opt,name=validation" json:"validation,omitempty"`
}

func (m *CreateUserResponse_Field) Reset()                    { *m = CreateUserResponse_Field{} }
func (m *CreateUserResponse_Field) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse_Field) ProtoMessage()               {}
func (*CreateUserResponse_Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *CreateUserResponse_Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserResponse_Field) GetValidation() string {
	if m != nil {
		return m.Validation
	}
	return ""
}

type GetSessionRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Role     string `protobuf:"bytes,3,opt,name=role" json:"role,omitempty"`
}

func (m *GetSessionRequest) Reset()                    { *m = GetSessionRequest{} }
func (m *GetSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSessionRequest) ProtoMessage()               {}
func (*GetSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetSessionRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetSessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetSessionRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type GetSessionResponse struct {
	Status  string                      `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Message string                      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Token   string                      `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	Fields  []*GetSessionResponse_Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
}

func (m *GetSessionResponse) Reset()                    { *m = GetSessionResponse{} }
func (m *GetSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSessionResponse) ProtoMessage()               {}
func (*GetSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetSessionResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetSessionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSessionResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetSessionResponse) GetFields() []*GetSessionResponse_Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetSessionResponse_Field struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Validation string `protobuf:"bytes,2,opt,name=validation" json:"validation,omitempty"`
}

func (m *GetSessionResponse_Field) Reset()                    { *m = GetSessionResponse_Field{} }
func (m *GetSessionResponse_Field) String() string            { return proto.CompactTextString(m) }
func (*GetSessionResponse_Field) ProtoMessage()               {}
func (*GetSessionResponse_Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *GetSessionResponse_Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetSessionResponse_Field) GetValidation() string {
	if m != nil {
		return m.Validation
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserRequest_Location)(nil), "user.CreateUserRequest.Location")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
	proto.RegisterType((*CreateUserResponse_Field)(nil), "user.CreateUserResponse.Field")
	proto.RegisterType((*GetSessionRequest)(nil), "user.GetSessionRequest")
	proto.RegisterType((*GetSessionResponse)(nil), "user.GetSessionResponse")
	proto.RegisterType((*GetSessionResponse_Field)(nil), "user.GetSessionResponse.Field")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/user.User/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := grpc.Invoke(ctx, "/user.User/GetSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _User_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x3d, 0x6f, 0xdb, 0x30,
	0x10, 0xb5, 0xac, 0x0f, 0xcb, 0xe7, 0xa5, 0x26, 0x8a, 0x96, 0x50, 0x51, 0x43, 0xd0, 0xa4, 0x49,
	0x83, 0x0b, 0x14, 0x05, 0xda, 0xa5, 0x28, 0xd0, 0x2e, 0x45, 0x07, 0x15, 0x1d, 0x3a, 0x05, 0x8c,
	0x7d, 0x0e, 0x84, 0x48, 0xa2, 0x43, 0x52, 0x09, 0xfc, 0x1f, 0xf2, 0x1f, 0xf2, 0x9b, 0xf2, 0x8f,
	0x02, 0x52, 0xa4, 0x2d, 0x44, 0xf0, 0x16, 0x64, 0xbb, 0x77, 0x77, 0x7c, 0xe4, 0x7b, 0x4f, 0x02,
	0xe8, 0x24, 0x8a, 0x62, 0x2f, 0xb8, 0xe2, 0x24, 0xd0, 0x75, 0xf6, 0x30, 0x85, 0xe5, 0x0f, 0x81,
	0x4c, 0xe1, 0x3f, 0x89, 0xa2, 0xc4, 0x9b, 0x0e, 0xa5, 0x22, 0x1f, 0x01, 0x76, 0x95, 0x90, 0xea,
	0xa2, 0x65, 0x0d, 0x52, 0x2f, 0xf5, 0xf2, 0x79, 0x39, 0x37, 0x9d, 0x3f, 0xac, 0x41, 0xf2, 0x01,
	0xe6, 0x35, 0x73, 0xd3, 0xa9, 0x99, 0xc6, 0xba, 0x61, 0x86, 0x6f, 0x21, 0xc4, 0x86, 0x55, 0x35,
	0xf5, 0xcd, 0xa0, 0x07, 0x24, 0x81, 0x78, 0xcf, 0xa4, 0xbc, 0xe3, 0x62, 0x4b, 0x83, 0xfe, 0x84,
	0xc3, 0xe4, 0x0d, 0xf8, 0xec, 0x0a, 0x69, 0x98, 0x7a, 0x79, 0x58, 0xea, 0x92, 0x10, 0x08, 0x04,
	0xaf, 0x91, 0x46, 0x66, 0xd3, 0xd4, 0xe4, 0x1b, 0xc4, 0x35, 0xdf, 0x30, 0x55, 0xf1, 0x96, 0xce,
	0x52, 0x2f, 0x5f, 0xac, 0xd3, 0xc2, 0xc8, 0x19, 0x3d, 0xbf, 0xf8, 0x6d, 0xf7, 0xca, 0xe3, 0x89,
	0xe4, 0x0b, 0xc4, 0xae, 0xab, 0xd9, 0x37, 0x95, 0x3a, 0x58, 0x5d, 0xa6, 0x26, 0x14, 0x66, 0x1b,
	0xde, 0xb5, 0x4a, 0x1c, 0xac, 0x20, 0x07, 0xb3, 0x47, 0x0f, 0xc8, 0xf0, 0x0a, 0xb9, 0xe7, 0xad,
	0x44, 0xf2, 0x0e, 0x22, 0xa9, 0x98, 0xea, 0xa4, 0xa5, 0xb1, 0x48, 0x13, 0x35, 0x28, 0xa5, 0x16,
	0x64, 0x89, 0x2c, 0xd4, 0xc6, 0x28, 0x7e, 0x8d, 0xad, 0x33, 0xc6, 0x00, 0xf2, 0x19, 0xa2, 0x5d,
	0x85, 0xf5, 0x56, 0xd2, 0x20, 0xf5, 0xf3, 0xc5, 0x7a, 0x35, 0x16, 0xd5, 0xdf, 0x58, 0xfc, 0xd4,
	0x6b, 0xa5, 0xdd, 0x4e, 0xbe, 0x42, 0x68, 0x1a, 0x5a, 0xcd, 0x20, 0x25, 0x53, 0x93, 0x15, 0xc0,
	0x2d, 0xab, 0xab, 0x6d, 0xef, 0x56, 0xff, 0x8e, 0x41, 0x27, 0xfb, 0x0f, 0xcb, 0x5f, 0xa8, 0xfe,
	0xa2, 0x94, 0xda, 0x25, 0x1b, 0xfa, 0x31, 0x38, 0xef, 0x5c, 0x70, 0xd3, 0x67, 0xc1, 0xb9, 0x98,
	0xfc, 0x53, 0x4c, 0xc6, 0xae, 0x21, 0xf7, 0xeb, 0xd8, 0x35, 0xbe, 0xf1, 0x05, 0xed, 0x5a, 0xdf,
	0x7b, 0x10, 0xe8, 0x28, 0xc8, 0x77, 0x80, 0x53, 0x30, 0xe4, 0xfd, 0x99, 0xef, 0x2f, 0xa1, 0xe7,
	0x32, 0xcc, 0x26, 0x9a, 0xe2, 0xf4, 0x58, 0x47, 0x31, 0x0a, 0xc3, 0x51, 0x8c, 0x75, 0x65, 0x93,
	0xcb, 0xc8, 0xfc, 0xc0, 0x9f, 0x9e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xb5, 0x84, 0x6e, 0xce,
	0x03, 0x00, 0x00,
}
